UserApp/urls.py
from django.urls import path
from . import views

app_name = "UserApp"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("<int:pk>/", views.mypage_view, name="mypage"),
    path("kakao", views.index, name="index"),
    path('kakaoLoginLogic/', views.kakaoLoginLogic),
    path('kakaoLoginLogicRedirect/', views.kakaoLoginLogicRedirect),
    path('kakaoLogout/', views.kakaoLogout),
    # path('kakaoLoginLogicRedirect/kakaoLogout', views.kakaoLogout)
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from cameraApp import views
from accounts.views import blog, posting

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("",views.index,name="index"),
    # path("users/",views.user_view, name='users'),
    # path("signup/",views.signup, name="signup"),
    #path("board/",views.PostLV.as_view(), name='post_list'), #앱과의 연결을 위하여 include 사용
    #path("board/",include('accounts.urls')),
    #path('blog/', blog, name='blog'),
    #path('blog/<int:pk>',posting, name="posting"),

    #path('waiting/',include('accounts.urls')),
    #path('waiting/test/', views.cameraTest, name='cameraTest'),


    # blogApp에서 공지사항 페이지 url -> post
    path('board/', include('blogApp.urls')),

    # tableApp에서 각 보드 Table 볼 수 있음
    path('table/',include('tableApp.urls')),

    path('mainpage/', include('indexApp.urls')),
    
    path('camera/',include('cameraApp.urls')),
    
    path('summernote/',include('django_summernote.urls')),

    path('table/',include('tableApp.urls')),
    path('auth/',include('UserApp.urls')),

    path('room/paper',views.exam_paper, name='exam_paper'),
    path('room/digital',views.exam_digital, name='exam_digital'),
    path('cheating/',views.CheatingListViewByUserId.as_view(), name='exam_result'),
    path('table/cheating',views.CheatingListView.as_view(), name='cheating_list'),    #응시자목록 보기
    
    path('post/',include('postApp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

indexApp/urls.py
from django.urls import path
from . import views

app_name = 'indexApp'

urlpatterns = [
    ## path('',views.board_list, name='board_list'),
    path('', views.index2, name='index'),
    #path('notice/', views.notice, name='notice'),
    path('room/',views.waiting_room, name='waiting'),

]

indexApp/models.py
from django.db import models

# Create your models here.

tableApp/models.py
from datetime import date
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings

# Create your models here.

# 시험 목록
class Test(models.Model):
    test_id = models.AutoField(primary_key=True, verbose_name='시험 코드')
    test_name = models.CharField(max_length=128, verbose_name='시험 과목')
    test_date = models.DateField(null=True, verbose_name='시험날짜')
    start_time = models.TimeField(verbose_name='시작시간')
    end_time = models.TimeField(verbose_name='종료시간')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    test_type = models.CharField(default="paper", db_column='test_type', max_length=10)
    head_count = models.IntegerField(verbose_name='인원수', default=0)
    
    def __str__(self):
        return self.test_name
    
    class Meta:
        db_table='testTable'
        verbose_name='testTable'
        verbose_name_plural='testTable'



# 응시자 목록: 입장 목록
class Examinee(models.Model):
    test_id = models.IntegerField(verbose_name='시험 코드')
    admin_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='admin_id', verbose_name='감독관id')
    examinee_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='examinee_id', verbose_name='응시자 아이디')
    entry_time = models.DateTimeField(auto_now_add=True, verbose_name='입장시간')
    test_type = models.CharField(default="paper", db_column='test_type', max_length=10)

    class Meta:
        db_table='Examinee'

indexApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def index2(request):
    return render(request, 'index2.html')

def waiting_room(request):
    return render(request, 'waiting_room.html')

indexApp/templates/exampage.html
exam page

indexApp/templates/footer.html
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

  <div class="footer-content">
    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>Nova</span>
          </a>
          <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
          <div class="social-links d-flex  mt-3">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bi bi-dash"></i> <a href="#">Home</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">About us</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Services</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Terms of service</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bi bi-dash"></i> <a href="#">Web Design</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Web Development</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Product Management</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Marketing</a></li>
            <li><i class="bi bi-dash"></i> <a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>

      </div>
    </div>
  </div>

  <div class="footer-legal">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Nova</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nova-bootstrap-business-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </div>
</footer><!-- End Footer -->
<!-- End Footer -->

indexApp/templates/header.html
<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
  <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

    <a href="/mainpage" class="logo d-flex align-items-center">
      <!-- Uncomment the line below if you also wish to use an image logo -->
      <!-- <img src="assets/img/logo.png" alt=""> -->
      <h1 class="d-flex align-items-center">Proctor</h1>
    </a>

    <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
    <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    <nav id="navbar" class="navbar">
      <ul>
        <li><a href="/mainpage" class="active">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="/board/notice_list">Notice</a></li>
        <li><a href="/table">Board</a></li>
        <li><a href="team.html">Team</a></li>
        <li><a href="/post">Blog</a></li>
        {% if user.userrole == 'admin' %}
          <li class="dropdown"><a href="#"><span>작성</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="/table/addTest">시험목록 작성</a></li>
              </li>
              <li><a href="#">공지사항 작성</a></li>
            </ul>
          </li>
        {% endif %}
        {% if user.userrole == 'student' %}
        <li class="dropdown"><a href="#"><span>작성</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
          <ul>
            <li><a href="/post/write">이의제기</a></li>
          </ul>
        </li>
        {% endif %}

        {% if user.is_authenticated%}
          <li class="dropdown"><a href="#"><span>{{user.username}}</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
          <ul>
            <li><a href="{% url 'UserApp:logout' %}">Logout</a></li>

        {% else %}
            <li><a href="{% url 'UserApp:login' %}">Login</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </nav><!-- .navbar -->

  </div>
</header><!-- End Header -->

indexApp/templates/waiting_room2.html

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Nova Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/Nova/assets/img/favicon.png" rel="icon">
  <link href="/static/Nova/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/Nova/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/Nova/assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Nova - v1.1.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="page-index">

  {% include 'header.html' %}


  <main id="main">
    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action" class="call-to-action">
      {% block contents %}
      <div class="container" data-aos="fade-up">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">

            <h3>Please enter your testId</h3>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            <div class="row-mt-5">
              {% csrf_token %}
              <form action="/table/enter" method="POST" enctype="multipart/form-data">
                <div>
                  <!-- {{ form.test_id }} -->
                  <input type="text" placeholder="시험ID를 입력하세요" name="test_id" value="{{ form.test_id }}" required>
                
              </div>
              </form>
            </div>
              <!-- <input id="id_test_id" type="text" class="form-control" placeholder="testId입력" name="test_id" value="{{ form.test_id }}" required> -->

            <br>
            <button type="submit">Get Started</button>

          </div>
        </div>

      </div>
      {% endblock %}
    </section><!-- End Call To Action Section -->
    

  </main><!-- End #main -->

  {% include 'footer.html' %}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/aos/aos.js"></script>
  <script src="/static/Nova/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/Nova/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/Nova/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/Nova/assets/js/main.js"></script>

</body>

</html>