UserApp/urls.py
from django.urls import path
from . import views

app_name = "UserApp"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("<int:pk>/", views.mypage_view, name="mypage"),
    path("kakao", views.index, name="index"),
    path('kakaoLoginLogic/', views.kakaoLoginLogic),
    path('kakaoLoginLogicRedirect/', views.kakaoLoginLogicRedirect),
    path('kakaoLogout/', views.kakaoLogout),
    # path('kakaoLoginLogicRedirect/kakaoLogout', views.kakaoLogout)
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from cameraApp import views
from accounts.views import blog, posting

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("",views.index,name="index"),
    # path("users/",views.user_view, name='users'),
    # path("signup/",views.signup, name="signup"),
    #path("board/",views.PostLV.as_view(), name='post_list'), #앱과의 연결을 위하여 include 사용
    #path("board/",include('accounts.urls')),
    #path('blog/', blog, name='blog'),
    #path('blog/<int:pk>',posting, name="posting"),

    #path('waiting/',include('accounts.urls')),
    #path('waiting/test/', views.cameraTest, name='cameraTest'),


    # blogApp에서 공지사항 페이지 url -> post
    path('board/', include('blogApp.urls')),

    # tableApp에서 각 보드 Table 볼 수 있음
    path('table/',include('tableApp.urls')),

    path('mainpage/', include('indexApp.urls')),
    
    path('camera/',include('cameraApp.urls')),
    
    path('summernote/',include('django_summernote.urls')),

    path('table/',include('tableApp.urls')),
    path('auth/',include('UserApp.urls')),

    path('room/paper',views.exam_paper, name='exam_paper'),
    path('room/digital',views.exam_digital, name='exam_digital'),
    path('cheating/',views.CheatingListViewByUserId.as_view(), name='exam_result'),
    path('table/cheating',views.CheatingListView.as_view(), name='cheating_list'),    #응시자목록 보기
    
    path('post/',include('postApp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):

    userphone = models.CharField(db_column='userphone', max_length=30)
    userrole = models.CharField(db_column='userrole', max_length=10, default="student")

UserApp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import redirect
from .models import User
import requests

import requests
import json



# Create your views here.
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        user_id = request.POST.get('username', None)
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증성공")
            login(request, user)
            request.session['user'] = user.username
            print(request.session['user'] )

        else:
            print("인증 실패")
    
    return render(request, "login.html")


def logout_view(request):
    logout(request)
    return redirect("UserApp:login")


def main_log(request):
    return redirect("UserApp:mainpage")


# 마이페이지 구현
def mypage_view(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user' : user
    }
    return render(request, 'UserApp/mypage.html', context)


def signup_view(request):

    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        # firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        userphone = request.POST["userphone"]
        userrole = request.POST["userrole"]
        email = request.POST["email"]

        user = User.objects.create_user(username, email, password)
        user.last_name = lastname
        # user.fist_name = firstname
        user.userrole = userrole
        user.userphone = userphone
        user.save()
        return redirect("UserApp:login")

    return render(request, "signup.html")



# 카카오톡 로그인 함수 #

def index(request):
    _context = {'check': False}
    if request.session.get('access_token'):
        _context['check'] = True
    return render(request, 'kakao_login/index.html', _context)
# 로그인 html 로 check 보내기?

def kakaoLoginLogic(request):
    # 카카오 디벨로퍼스 앱 생성 후 얻은 키 (로컬에 맞게)
    _restApiKey = '보안필요'
    # 카카오 디벨로퍼스에 등록 필요
    _redirectUrl = 'http://127.0.0.1:8000/auth/kakaoLoginLogicRedirect'
    _url = f'https://kauth.kakao.com/oauth/authorize?client_id={_restApiKey}&redirect_uri={_redirectUrl}&response_type=code'
    return redirect(_url)


def kakaoLoginLogicRedirect(request):
    _qs = request.GET['code']
    print(_qs)
    url = 'https://kauth.kakao.com/oauth/token'
    rest_api_key = '보안' # 프록터 애플리케이션 키
    redirect_uri = 'http://127.0.0.1:8000/auth/kakaoLoginLogicRedirect'
    authorize_code = _qs # 전체 시스템 관리자 인증 코드(6시간마다 바뀜)

    data = {
        'grant_type':'authorization_code',
        'client_id':rest_api_key, #REST API KEY
        'redirect_uri':redirect_uri,
        'code': authorize_code, #로그인 시 필요한 코드
        }

    response = requests.post(url, data=data)
    tokens = response.json()
    print(tokens)

    filename = 'kakao_json/kakao_code_{}.json'.format(request.session['user'])
    with open(filename,"w+") as fp:
        json.dump(tokens, fp)


    return render(request, 'kakao_login/kakaoLoginSuccess.html')


def kakaoLogout(request):
    _token = request.session['access_token']
    _url = 'https://kapi.kakao.com/v1/user/logout'
    _header = {
      'Authorization': f'bearer {_token}'
    }
    _res = requests.post(_url, headers=_header)
    _result = _res.json()
    if _result.get('id'):
        del request.session['access_token']
        return render(request, "indexApp:index")
    else:
        return render(request, 'kakao_login/logoutError.html')

UserApp/templates/login.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>로그인 페이지</title>-->
<!--</head>-->
<!--<body>-->
<!--<p>로그인 페이지</p>-->
<!--</body>-->
<!--</html>-->

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Proctor</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/Nova/assets/img/favicon.png" rel="icon">
  <link href="/static/Nova/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/Nova/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/Nova/assets/css/main.css" rel="stylesheet">
  <style>
    /* body{
        min-height:100vh;
        background: -webkit-gradient(linear, left bottom, right top, from(#92b5db), to(#1d466c));
        background: -webkit-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: -moz-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: -o-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: linear-gradient(to top right, #92b5db 0%, #1d466c 100%);
    } */

    .input-form {
        max-width: 680px;

        margin-top: 80px;
        padding: 32px;

        background: #fff;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
        -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
        box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)

    }
    .wrap1{
        text-align:center;
    }

</style>

  <!-- =======================================================
  * Template Name: Nova - v1.1.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="page-index">

{% include 'header.html' %}

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('/static/Nova/assets/img/blog-header.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center">

        <h2>Log in</h2>
        <ol>
          <li><a href="/mainpage/">Home</a></li>
          <li>Log in</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->
<br>

<!-- <div class="container">
  <div class="login">
      <div class="row my-3">
      <br>
          {% if user.is_authenticated %}
              <h3>Welcome to PROCTOR!</h3>
              <br>
              {{ user.username }}님 환영합니다.
              <a href="{% url 'UserApp:logout' %}">로그아웃</a>


                  {% if user.userrole == 'admin' %}
                       {% if check %}
                           <h1>카카오톡 로그인 성공</h1>
                           <form action="{% url 'UserApp:kakaoLogout' %}" method="GET">
                               <input type="submit" value="카카오 로그아웃 및 연결 해제"/>
                           </form>
                       {% else %}
                           <div>
                               <h1>카카오톡 로그인</h1>
                              <p> 관리자 {{ user.username }} 님,
                                  카카오톡 알림을 받기 위해서 카카오톡 로그인을 진행해주세요 </p>
                               <form action="{% url 'UserApp:index' %}" method="GET">
                               <input type="image" src="/static/Nova/assets/img/kakao.png"/>
                               </form>
                           </div>
                       {% endif %}
                  <a href="{% url 'UserApp:index' %}">카카오톡 로그인</a> -->
                  <!-- {% endif %} -->
                  
          <!-- {% else %}
          <h4><a href="{% url 'UserApp:signup' %}">Signup</a></h4>

          <form action="" method="POST">
              {% csrf_token %}
              <h2>Log-in</h2>
              <h4>ID</h4>
              <input name="username" type="text" placeholder="ID">
              <h4>Password</h4>
              <input name="password" type="password" placeholder="password">
              <input type="submit" value="로그인">
          </form>
          {% endif %}
          
      </div>
  </div>
</div>   -->

<div class="container">
    <div class="input-form-backgroud row">
        <div class="input-form col-md-12 mx-auto">
            <div class="login">
                <div class="row my-3">
                    <br>
                    {% if user.is_authenticated %}
                    <div class="wrap1">
                        <h3 class="mb-3" style="color:#1d466c">Welcome to <b>PROCTOR</b>!</h3>
                    <h5><b>{{ user.username }}</b> 님 환영합니다</h5><br>
                    </div>
                    {% if user.userrole == 'admin' %}
<!--                        {% if check %}-->
<!--                            <h1>카카오톡 로그인 성공</h1>-->
<!--                            <form action="{% url 'user:kakaologout' %}" method="GET">-->
<!--                                <input type="submit" value="카카오 로그아웃 및 연결 해제"/>-->
<!--                            </form>-->
<!--                        {% else %}-->
                            <div class="container">
<!--                                <h4 class="mb-3"style="color:#1d466c"><b>kakao login</b></h4>-->
                                <div class="wrap1">
                                <p> 
                                    카카오톡 알림을 받기 위해서 카카오톡 로그인을 진행해주세요 </p>
                                <form action="{% url 'UserApp:index'%}" method="GET">
                                <input type="image" src="/static/Nova/assets/img/startKakao.png"/>
                                </form>
                                </div>
                            </div>
<!--                        {% endif %}-->
<!--                    <a href="{% url 'UserApp:index' %}">카카오톡 로그인</a>-->
                        {% endif %}
                        <a href="{% url 'UserApp:logout' %}"><b>로그아웃</b></a>
                    {% else %}
                        <h4><a href="{% url 'UserApp:signup' %}">Signup</a></h4>

                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="wrap1">
                        <h2 class="mb-3" style="color:#1d466c"><b>Login</b></h2>
                    </div>
                    <h4>ID</h4>
                    <input name="username" class="form-control" type="text" placeholder="ID">
                    <br>
                    <h4>Password</h4>
                    <input name="password" class="form-control" type="password" placeholder="password">
                    <br>
                    <button class="btn btn-primary btn-lg btn-block" type="submit">로그인</button>
                </form>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    <footer class="my-3 text-center text-small">
             <p class="mb-1">&copy; 2022 PROCTOR</p>
    </footer>
</div>
</main>



<script>

var ws = new WebSocket('ws://127.0.0.1:8000');
ws.onopen = (event) => {
let sendData = { event: 'open' }
ws.send(JSON.stringify(sendData));
}
ws.onmessage = (event) => {
let recData = JSON.parse(event.data);
switch (recData.event) {
  case 'response':
    console.log(recData.data);
    break;
}
}

function myOnClick() {
let sendData = {
  event: 'request',
  data: 'some data...'
};
ws.send(JSON.stringify(sendData));
}
</script>




  {% include 'footer.html' %}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/aos/aos.js"></script>
  <script src="/static/Nova/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/Nova/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/Nova/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/Nova/assets/js/main.js"></script>

</body>

</html>

UserApp/templates/mypage.html
내 정보확인 마이페이지

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

UserApp/templates/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Proctor</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/Nova/assets/img/favicon.png" rel="icon">
  <link href="/static/Nova/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Vendor CSS Files -->
  <link href="/static/Nova/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/Nova/assets/css/main.css" rel="stylesheet">
<!-- 새로 추가해야할 것! -->
<style>
    /* body{
        min-height:100vh;
        background: -webkit-gradient(linear, left bottom, right top, from(#92b5db), to(#1d466c));
        background: -webkit-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: -moz-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: -o-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
        background: linear-gradient(to top right, #92b5db 0%, #1d466c 100%);
    } */

    .input-form {
        max-width: 680px;

        margin-top: 80px;
        padding: 32px;

        background: #fff;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
        -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
        box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)
    }
    .wrap1{
        text-align:center;
    }

</style>
  <!-- =======================================================
  * Template Name: Nova - v1.1.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="page-index">

{% include 'header.html' %}

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('assets/img/blog-header.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center">

        <h2>Sign up</h2>
        <ol>
          <li><a href="/mainpage/">Home</a></li>
          <li>Sign up</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->
<br>

<!-- 바뀐 것! -->
<div class="container">
    <div class="input-form-background row">
        <div class="input-form col-md-12 mx-auto">
            <div class="wrap1">
            <h4 class="mb-3" style="color:#1d466c"><b>Welcome to PROCTOR!</b></h4>
            </div>
            <form class="validation-form" action="" method="post">
                <div class="row">
                    <div class="mb-3">
                        {% csrf_token %}
                            <label>아이디</label>
                            <input type="text" class= "form-control" name="username" placeholder="ID">
                            <br>
                            <label>비밀번호</label>
                            <input type="password" class= "form-control" name="password" placeholder="password">
                            <br>
                            <label>이름</label>
                            <input type="text" class= "form-control" name="lastname" placeholder="name">
                            <br>
                            <label>이메일</label>
                            <input type="text" class= "form-control" name="email" placeholder="email">
                            <br>
                            <label>전화번호</label>
                            <input type="tel" class= "form-control" name="userphone" placeholder="11자리 입력">
                            <br>
                            <div class="wrap1">
                            <h6 style="color:#1d466c"><b>WHAT'S YOUR ROLE?</b></h6>
                            학생<input type="radio" name="userrole" value="student">
                            관리자<input type="radio" name="userrole" value="admin">
                            <br><br>
                            </div>
<!--                                <input type="submit" value="회원가입">-->
                            <button class="btn btn-primary btn-lg btn-block" type="submit">회원가입</button>
                            <br>

<!-- 
    <div class="container">
        <h4>Welcome to Proctor!</h4>
        <div class="signup">
            <form action="" method="POST">
                {% csrf_token %}
                <table width="300" border="1" cellpadding="2" cellspacing="0">
                <tbody>
                <tr>
                    <td>아이디</td>
                    <td><input type="text" name="username"></td>
                </tr>
                <tr>
                    <td>비밀번호</td>
                    <td><input type="password" name="password"></td>
                </tr>
                <tr>
                    <td>이름</td>
                    <td><input type="text" name="lastname"></td>
                </tr>
                <tr>
                    <td>이메일</td>
                    <td><input type="email" name="email"></td>
                </tr>
                <tr>
                    <td>전화번호</td>
                    <td><input type="tel" name="userphone"></td>
                </tr>
                <tr>
                    <td>역할</td>
                    <td>
                    학생<input type="radio" name="userrole" value="student">
                    관리자<input type="radio" name="userrole" value="admin">
                    </td>
                </tr>
                </tbody>
                </table>
                <input type="submit" value="회원가입">
            </form>
        </div>
    </div> -->
</div>
</div>
</form>
</div>
</div>
<footer class="my-3 text-center text-small">
<p class="mb-1">&copy; 2022 PROCTOR</p>
</footer>
</div>


<br>

    {% include 'footer.html' %}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/aos/aos.js"></script>
  <script src="/static/Nova/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/Nova/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/Nova/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/Nova/assets/js/main.js"></script>

</body>

</html>
