UserApp/urls.py
from django.urls import path
from . import views

app_name = "UserApp"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("<int:pk>/", views.mypage_view, name="mypage"),
    path("kakao", views.index, name="index"),
    path('kakaoLoginLogic/', views.kakaoLoginLogic),
    path('kakaoLoginLogicRedirect/', views.kakaoLoginLogicRedirect),
    path('kakaoLogout/', views.kakaoLogout),
    # path('kakaoLoginLogicRedirect/kakaoLogout', views.kakaoLogout)
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from cameraApp import views
from accounts.views import blog, posting

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("",views.index,name="index"),
    # path("users/",views.user_view, name='users'),
    # path("signup/",views.signup, name="signup"),
    #path("board/",views.PostLV.as_view(), name='post_list'), #앱과의 연결을 위하여 include 사용
    #path("board/",include('accounts.urls')),
    #path('blog/', blog, name='blog'),
    #path('blog/<int:pk>',posting, name="posting"),

    #path('waiting/',include('accounts.urls')),
    #path('waiting/test/', views.cameraTest, name='cameraTest'),


    # blogApp에서 공지사항 페이지 url -> post
    path('board/', include('blogApp.urls')),

    # tableApp에서 각 보드 Table 볼 수 있음
    path('table/',include('tableApp.urls')),

    path('mainpage/', include('indexApp.urls')),
    
    path('camera/',include('cameraApp.urls')),
    
    path('summernote/',include('django_summernote.urls')),

    path('table/',include('tableApp.urls')),
    path('auth/',include('UserApp.urls')),

    path('room/paper',views.exam_paper, name='exam_paper'),
    path('room/digital',views.exam_digital, name='exam_digital'),
    path('cheating/',views.CheatingListViewByUserId.as_view(), name='exam_result'),
    path('table/cheating',views.CheatingListView.as_view(), name='cheating_list'),    #응시자목록 보기
    
    path('post/',include('postApp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tableApp/urls.py
from django.urls import path
from . import views
app_name = 'tableApp'

urlpatterns = [
    
    path('addTest/',views.add_testInfo, name="add_testInfo"), #시험목록 작성
    path('',views.TestListView.as_view(), name='test_list'),  #시험목록 list로 보기
    
    path('room/',views.add_examineeInfo, name='add_examinee'),                      #응시자 정보 DB에 넣기
    path('enter/',views.ExamineeListView.as_view(), name='examinee_list'),    #응시자목록 보기
]

tableApp/models.py
from datetime import date
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings

# Create your models here.

# 시험 목록
class Test(models.Model):
    test_id = models.AutoField(primary_key=True, verbose_name='시험 코드')
    test_name = models.CharField(max_length=128, verbose_name='시험 과목')
    test_date = models.DateField(null=True, verbose_name='시험날짜')
    start_time = models.TimeField(verbose_name='시작시간')
    end_time = models.TimeField(verbose_name='종료시간')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    test_type = models.CharField(default="paper", db_column='test_type', max_length=10)
    head_count = models.IntegerField(verbose_name='인원수', default=0)
    
    def __str__(self):
        return self.test_name
    
    class Meta:
        db_table='testTable'
        verbose_name='testTable'
        verbose_name_plural='testTable'



# 응시자 목록: 입장 목록
class Examinee(models.Model):
    test_id = models.IntegerField(verbose_name='시험 코드')
    admin_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='admin_id', verbose_name='감독관id')
    examinee_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='examinee_id', verbose_name='응시자 아이디')
    entry_time = models.DateTimeField(auto_now_add=True, verbose_name='입장시간')
    test_type = models.CharField(default="paper", db_column='test_type', max_length=10)

    class Meta:
        db_table='Examinee'

tableApp/forms.py
from django import forms
from .models import Test, Examinee

class TestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TestForm, self).__init__(*args, **kwargs)
        self.fields['test_name'].label = '시험과목'
        self.fields['test_name'].widget.attrs.update({
            'placeholder':'시험과목을 입력해주세요.',
            'class':'form-control',
            'autofocus':True,
        })

    class Meta:
        model = Test
        fields = ['test_name','test_date','start_time','end_time', 'test_type','head_count']


class ExamineeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ExamineeForm, self).__init__(*args, **kwargs)
        self.fields['test_id'].label = '시험코드'
        self.fields['test_id'].widget.attrs.update({
            'placeholder':'시험코드를 입력해주세요.',
            'class':'form-control',
            'autofocus':True,
        })
    class Meta:
        model = Examinee
        fields = ['test_id']


tableApp/views.py
from asyncio.windows_events import NULL
from multiprocessing import context
from django.shortcuts import render
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView
from .models import Test, Examinee
from .forms import ExamineeForm, TestForm
from UserApp.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def view_board(request):
    return render(request, "view_table.html")

@login_required
def add_testInfo(request):
    if request.method == 'POST':
        form = TestForm(request.POST)
        user = request.session['user']
        user_id = User.objects.get(username = user)
        print(form)
        if form.is_valid():            
            test = form.save()
            test.writer = user_id
            print(test.test_type)
            test.save()
            return redirect('/table')
    else:
        print("GET")
        form = TestForm()
    return render(request, 'add_test.html', {'form': form})

class TestListView(ListView):
    model = Test
    paginate_by = 5
    template_name = 'view_table.html'
    context_object_name = 'view_table'

    def get_queryset(self):
        view_table = Test.objects.order_by('-test_id')
        return view_table

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        
        return context

def view_list(request):
    boards = Test.objects.all().order_by('-test_id')
    return render(request, 'test_list.html',{"boards":boards})

#waiting_room 
def wait(request):
    return render(request, "waiting_room.html")

#입장목록 DB에 넣기
def add_examineeInfo(request):
    print("add_examinee?")
    if request.method == 'POST':
        form = ExamineeForm(request.POST)
        user = request.session['user']
        user_id = User.objects.get(username = user)
        print("POST")
        print(form)
        if form.is_valid():            
            examinee = form.save()
            examinee.examinee_id = user_id
            test = Test.objects.get(test_id=examinee.test_id)
            if test.writer==None:
                messages.error(request,"잘못된 시험코드입니다.")
                return render(request, 'waiting_room.html', {'form':form})
            examinee.admin_id = test.writer
            examinee.test_type = test.test_type
            print(examinee.examinee_id)
            examinee.save()
            print(test.test_type)
            if (test.test_type=='paper'):
                return redirect('exam_paper')
            elif (test.test_type=='digital'):
                return redirect('exam_digital')
            return redirect('/table/enter')
    else:
        print("GET")
        form = ExamineeForm()
    return render(request, 'waiting_room.html', {'form': form})

#입장목록 보기
class ExamineeListView(ListView):
    model = Examinee
    paginate_by = 5
    template_name = 'examinee_list.html'
    context_object_name = 'examinees'

        # 검색 기능 추가
    def get_queryset(self):
        search_keyword = self.request.GET.get('q','')
        search_type = self.request.GET.get('type','')
        examinees = Examinee.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword)>1:
                if search_type=='test_id':
                    search_examinee_list = examinees.filter(test_id__exact=search_keyword)
                elif search_type=='examinee_id':
                    search_examinee_list = examinees.filter(examinee_id__exact=search_keyword)
                elif search_type=='writer':
                    search_examinee_list = examinees.filter(writer__exact=search_keyword)
                return search_examinee_list
            else:
                messages.error(self.request,'검색어는 2글자 이상 입력해주세요')
        return examinees

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q','')
        search_type = self.request.GET.get('type','')
        if len(search_keyword)>1:
            context['q'] = search_keyword
        context['type'] = search_type

        return context



        

def exam_paper(request):
    return render(request, "paper_exam.html")

def exam_digital(request):
    return render(request, "digital_exam.html")



tableApp/templates/add_test.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Nova Bootstrap Template - Blog</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/Nova/assets/img/favicon.png" rel="icon">
  <link href="/static/Nova/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Vendor CSS Files -->
  <link href="/static/Nova/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/Nova/assets/css/main.css" rel="stylesheet">


  <!-- =======================================================
  * Template Name: Nova - v1.1.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<style>

        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap');

        label{
          font-family: 'Noto Sans KR', sans-serif;
        }

        /* body{
            min-height:100vh;
            background: -webkit-gradient(linear, left bottom, right top, from(#92b5db), to(#1d466c));
            background: -webkit-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
            background: -moz-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
            background: -o-linear-gradient(bottom left, #92b5db 0%, #1d466c 100%);
            background: linear-gradient(to top right, #92b5db 0%, #1d466c 100%);
        } */

        .input-form {
            max-width: 680px;

            margin-top: 80px;
            padding: 32px;

            background: #fff;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
            -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
            box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)
        }
        .wrap1{
            text-align:center;
        }

  </style>
</head>

<body class="page-blog">

  {% include 'header.html' %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('/static/Nova/assets/img/portfolio-header.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center">

        <h2>Board</h2>
        <ol>
          <li><a href="/mainpage">Home</a></li>
          <li>Board</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->


<link rel="stylesheet" href="/static/bootstrap/examples/checkbox.css" type="text/css">

{% block contents%}
<div class="container">
  <div class="input-form-background row">
    <div class="input-form col-md-12 mx-auto">
      <div class="container">
        <div class="row mt-5">
          <div class="col-12">
            <div class="wrap1">
              <h4 style="color:#1d466c"><b>시험 목록</b></h4>
            </div>
          </div>
        </div>
      </div>
      <div class="row-mt-5">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div>
            <div>
              <div>
                <!-- <div>
                  <label id="id_name"> 시험 과목 </label>
                  <input id="id_name" type="text" class="form-control" placeholder="시험 과목" name="text[]" value="{{ form.test_name }}" required> -->
                    시험 과목 : {{ form.test_name }}
              </div>
            </div>
          </div>
          <div>
              <label id="id_test_date">시험 날짜: </label>
              <!-- {{ form.test_date|date:'Y-m-d' }} -->
              <input id="id_test_date" type="date" class="form-control" placeholder="연도,월,일" name="test_date" value="{{ form.test_date|date:'Y-m-d' }}" required>
          </div>
          <div>
              <label id="id_start_time"> 시작 시간: </label>
          <!-- {{ form.start_time }} -->
              <input id="id_start_time" type="time" class="form-control" placeholder="시,분" name="start_time" value="{{ form.start_time|time:'H:M' }}" required>
          </div>
          <div>
              <label id="id_end_time"> 종료 시간: </label>
        <!-- {{ form.end_time }} -->
              <input id="id_end_time" type="time" class="form-control" placeholder="시,분" name="end_time" value="{{ form.end_time|time:'H:M' }}" required>
          </div>
          <div>
                <label id="id_head_count"> 인원:  </label>
            <!-- {{ form.end_time }} -->
                <input id="id_head_count" type="number" class="form-control" name="head_count" value="{{ form.head_count }}">
           
          </div>
          <div class="text-align" style="margin-top: 10px;">
            <div class="text-right" style="margin-top: 10px;">
                <label id="id_test_type">
                    <input id="id_test_type" type="radio" name="test_type" value="paper">Paper Exam
                    <input id="id_test_type" type="radio" name="test_type" value="digital">Digital Exam
            <!-- {{ form.test_type }} -->
                </label>
              <br>
            </div>
          </div>
            <br>
            {% if edit %}
            <button class="btn btn-primary btn-lg btn-block" type="submit" id="write" class="btn btn-sm">{{ edit }}</button>
            {% else %}
            <button class="btn btn-primary btn-lg btn-block" type="submit" id="write" class="btn btn-sm">작성하기</button>
            {% endif %}
            <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">
        </div>
        </form>
      </div>
   </div>
 </div>
</div>
    <footer class="my-3 text-center text-small">
      <p class="mb-1">&copy; 2022 PROCTOR</p>
    </footer>
</div>
{% endblock%}
{% include 'footer.html' %}

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/Nova/assets/vendor/aos/aos.js"></script>
<script src="/static/Nova/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="/static/Nova/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="/static/Nova/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="/static/Nova/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="/static/Nova/assets/js/main.js"></script>

</body>

</html>

tableApp/templates/waiting_room.html

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Nova Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/Nova/assets/img/favicon.png" rel="icon">
  <link href="/static/Nova/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/Nova/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="/static/Nova/assets/vendor/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/Nova/assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Nova - v1.1.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="page-index">

  {% include 'header.html' %}


  <main id="main">
    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action" class="call-to-action">
      {% block contents %}
      <div class="container" data-aos="fade-up">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">

            <h3>Please enter your testId</h3>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            <div class="row-mt-5">
              
              <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                  <!-- <label for="{{ form.test_id }}"> {{ form.test_id }} </label> -->
                  <input type="number" placeholder="시험Id" value="{{ form.test_id }}" required>
                  <br>
                  <div>
                  <button type="submit" id="write" class="btn-get-started">Get Started</button>
                  </div>
                </div>
              </form>
            </div>
              <!-- <input id="id_test_id" type="text" class="form-control" placeholder="testId입력" name="test_id" value="{{ form.test_id }}" required> -->



          </div>
        </div>

      </div>
      {% endblock %}
    </section><!-- End Call To Action Section -->
    

  </main><!-- End #main -->

  {% include 'footer.html' %}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/Nova/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/aos/aos.js"></script>
  <script src="/static/Nova/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/Nova/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/Nova/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/Nova/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/Nova/assets/js/main.js"></script>

</body>

</html>